/* eslint-disable react/jsx-filename-extension */
import Head from 'next/head';
import axios from 'axios';
import styles from '../styles/Home.module.css';
import HomeContainer from '../container/home';

function Home({ cityTemp }) {
  console.log(cityTemp);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer cityTemp={cityTemp} />
    </div>
  );
}

Home.getInitialProps = async () => {
  const saoPauloWeatherId = 3448433;
  const response = await axios.get(`http://api.openweathermap.org/data/2.5/weather?id=${saoPauloWeatherId}&units=metric&appid=65ac01c6754549317ac81df237632d7c`);

  return { cityTemp: response.data?.main?.temp };
};

export default Home;
